### ISSUE TITLE
SPIC data

### ISSUE THREAD

**Issue by a462428** [cs-chan/Exclusively-Dark-Image-Dataset#3] opened 2019-09-02 03:40 UTC
Hi, really thx for your useful data!
Besides, I thought SPIC is good. Is it convenient to offer data after using “SPIC” cuz I don’t have matlab Q_Q. Thx!

**Comment by cs-chan** [comment] 2019-09-05 19:22
Hi, thx for interest. May I know what to you mean by “offer data after using SPIC”?

**Comment by loqoella** [comment] 2020-03-26 00:05
Are the data in ExDark raw data?

**Comment by yploh** [comment] 2020-03-26 09:27
> Are the data in ExDark raw data?

Duplicate of #10

**Closed as completed** 2020-03-26 09:54 UTC
